global:
  scrape_interval: 5s  # как часто Prometheus забирает метрики

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['YOUR_APP_IP:9100']  # <-- Node exporter на VM-1

  - job_name: 'app'
    static_configs:
      - targets: ['YOUR_APP_IP:8000']  # <-- Flask-приложение на VM-1
    metrics_path: '/metrics'
