global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['YOUR_APP_IP:9100']

  - job_name: 'app'
    static_configs:
      - targets: ['YOUR_APP_IP:8000']
    metrics_path: '/metrics'
